from classes_chinois import Vocabulary

dq_vocabulary = {

}

#dq_vocabulary[""] = Vocabulary("", "", "", 1)

dq_vocabulary["回去"] = Vocabulary("hui2 qu4", "回去", "go back", 1)
dq_vocabulary[""] = Vocabulary("hui2 lai2", "回来", "come back", 1)
dq_vocabulary["行不行"] = Vocabulary("xing2 bu4 xing2", "行不行", "will that work ? / can you do it or not ?(ironic)", 2)
dq_vocabulary["然后"] = Vocabulary("ran2 hou4", "然后", "and then, used in the middle of a sequence of events", 3)
dq_vocabulary["那边"] = Vocabulary("na4 bian", "那边", "over there", 1)
dq_vocabulary["二维码"] = Vocabulary("er4 wei2 ma3", "二维码", "QR code", 2)
dq_vocabulary["唱"] = Vocabulary("chang4", "唱", "sing", 1)
dq_vocabulary["扫"] = Vocabulary("sao3", "扫", "scan", 1)
dq_vocabulary["歌"] = Vocabulary("ge1", "歌", "a song", 1)
dq_vocabulary["烦人"] = Vocabulary("fan2 ren2", "烦人", "annoying", 2) 
dq_vocabulary["钥匙"] = Vocabulary("yao4 shi", "钥匙", "key", 1)
dq_vocabulary["小摊"] = Vocabulary("xiao3 tan1", "小摊", "vendor's stall, a stall", 2)
dq_vocabulary["一般"] = Vocabulary("yi4 ban1", "一般", "generally", 1)
dq_vocabulary["都"] = Vocabulary("dou1", "都", "all", 1)
dq_vocabulary["我个人"] = Vocabulary("wo3 ge ren2", "我个人", "I personally (think of) ... ", 2)
dq_vocabulary["很少"] = Vocabulary("hen3 shao3", "很少", "Very little, seldomly", 2)
dq_vocabulary["几乎"] = Vocabulary("ji1 hu1", "几乎", "Almost, nearly, practically", 2)
dq_vocabulary["逛"] = Vocabulary("guang1", "逛", "a stroll", 1)
dq_vocabulary["想到"] = Vocabulary("xiang3 dao4", "想到", "Think of, anticipate", 2)
dq_vocabulary["我没想到"] =Vocabulary("wo3 mei2 xiang3 dao4", "我没想到", "I didn't think that ..., I didn't anticipate ...", 3)
dq_vocabulary["商场"] = Vocabulary("shang1 chang3", "商场", "shopping mall", 1)

dq_vocabulary["因为"] = Vocabulary("yin1 wei4", "因为", "because", 1)
dq_vocabulary["我比较喜欢"] = Vocabulary("wo3 bi3 jiao4 xi3 huan1", "我比较喜欢", "I prefer", 2)
dq_vocabulary["比较"] = Vocabulary("bi3 jiao4", "比较", "In comparaison to ...", 2)
dq_vocabulary["龙"] = Vocabulary("long2", "龙", "dragon", 1)
dq_vocabulary["一些"] = Vocabulary("yi1 xie1", "一些", "some", 1)
dq_vocabulary["有些"] = Vocabulary("you3 xie1", "有些", "There are some", 1)
dq_vocabulary["刚刚"] = Vocabulary("gang1 gang", "刚刚", "Just now", 1)


dq_vocabulary["甜甜圈"] = Vocabulary("tian2 tian2 quan1", "甜甜圈", "Doughnut", 1)
dq_vocabulary["想象"] = Vocabulary("xiang3 xiang4", "想象", "to imagine, to fancy", 2)
dq_vocabulary["热闹"] = Vocabulary("re4 nao", "热闹", "lively, busy", 2)
dq_vocabulary["等"] = Vocabulary("deng3", "等", "to wait for", 1)
dq_vocabulary["着"] = Vocabulary("zhe", "着", "particle indicating an action in progress and that will continue for a while", 1)
dq_vocabulary["我在等着"] = Vocabulary("wo3 zai4 deng3 zhe", "我在等着", "I'm waiting for ... (the wait will continue for a while)", 2)
dq_vocabulary["过马路"] = Vocabulary("guo4 ma3 lu4", "过马路", "to cross the street", 1)

dq_vocabulary["支付宝"] = Vocabulary("zhi1 fu4 bao3", "支付宝", "alipay", 1)
dq_vocabulary["充电宝"] = Vocabulary("chong1 dian4 bao3", "充电宝", "power bank", 1)
dq_vocabulary["借"] = Vocabulary("jie4", "借", "borrow", 1)
dq_vocabulary["毛巾"] = Vocabulary("mao2 jin1", "毛巾", "towel", 1)
dq_vocabulary["马上"] = Vocabulary("ma3 shang4", "马上", "almost, about to", 2)
dq_vocabulary["还是"] = Vocabulary("hai2 shi4", "还是", "or", 1)

dq_vocabulary["春天"] = Vocabulary("chun1 tian1", "春天", "spring", 1)
dq_vocabulary["夏天"] = Vocabulary("xia4 tian1", "夏天", "summer", 1)
dq_vocabulary["秋天"] = Vocabulary("qiu1 tian1", "秋天", "autumn", 1)
dq_vocabulary["冬天"] = Vocabulary("dong1 tian1", "冬天", "winter", 1)
dq_vocabulary["花"] = Vocabulary("hua1", "花", "flower", 1)

dq_vocabulary["带"] = Vocabulary("dai4", "带", "to bring", 1)
dq_vocabulary["得"] = Vocabulary("dei3", "得", "should/ need to/ have to/ ought to (one character)", 2)
dq_vocabulary["花"] = Vocabulary("hua1", "花", "spend money/time", 1)

dq_vocabulary["也是"] = Vocabulary("ye3 shi4", "也是", "is also", 1)
dq_vocabulary["这里"] = Vocabulary("zhe4 li3", "这里", "here / there is", 1)
dq_vocabulary["还有"] = Vocabulary("hai2 you3", "还有", "in addition / furthermore / also", 3)
dq_vocabulary["这里还有"] = Vocabulary("zhe4 li3 hai2 you3", "这里还有", "There is also ... (another place, this place)", 2)
dq_vocabulary["地方"] = Vocabulary("di4 fang1", "地方", "place", 2)
dq_vocabulary["可以"] = Vocabulary("ke3 yi3", "可以", "may, can, being allowed to", 1)
dq_vocabulary["酒吧"] = Vocabulary("jiu3 ba1", "酒吧", "bar / saloon", 2)
dq_vocabulary["也"] = Vocabulary("ye3", "也", "also / too", 1)

dq_vocabulary["困了"] = Vocabulary("kun4 le", "困了", "sleepy now", 2)
dq_vocabulary["你困了吗"] = Vocabulary("ni3 kun4 le ma", "你困了吗", "are you sleepy ?", 2)

dq_vocabulary["圣诞"] = Vocabulary("sheng4 dan4", "圣诞", "Christmas", 1)
dq_vocabulary["和"] = Vocabulary("he2", "和", "and", 1)
dq_vocabulary["聊天"] = Vocabulary("liao2 tian1", "聊天", "chat / gossip", 2)
dq_vocabulary["挺"] = Vocabulary("ting3", "挺", "quite (quite happy)", 3)
dq_vocabulary["觉得"] = Vocabulary("jue2 de", "觉得", "to think / to feel (about something)", 3)
dq_vocabulary["看到没"] = Vocabulary("kan4 dao4 mei2", "看到没", "Did you see that?", 2)
dq_vocabulary["练"] = Vocabulary("lian4", "练", "to pratice / to drill / to perfect", 1)
dq_vocabulary["他在练"] = Vocabulary("ta1 zai4 lian4", "他在练", "He is practising ... (this skill)", 2)
dq_vocabulary["一个喝茶的地方"] = Vocabulary("yi1 ge he1 cha2 de di4 fang1", "一个喝茶的地方", "a place to drink tea", 2)

dq_vocabulary["害羞"] = Vocabulary("hai4 xiu1", "害羞", "shy", 3)
dq_vocabulary["小孩"] = Vocabulary("xiao3 hai2", "小孩", "child", 2)
dq_vocabulary["所以"] = Vocabulary("suo3 yi3", "所以", "so / therefore (2 words)", 2)
dq_vocabulary["会"] = Vocabulary("hui4", "会", "can, know how to, skilled enough to do something", 1)
dq_vocabulary["慢"] = Vocabulary("man4", "慢", "slow", 1)
dq_vocabulary["慢点"] = Vocabulary("man4 dian3", "慢点", "slower", 1)
dq_vocabulary["话"] = Vocabulary("hua4", "话", "language / dialect", 1)
dq_vocabulary["能"] = Vocabulary("neng2", "能", "can, having the ability to do something, being able to", 1)
dq_vocabulary["听懂"] = Vocabulary("ting1 dong3", "听懂", "to understand (on hearing), to understand what is spoken", 1)
dq_vocabulary["就是"] = Vocabulary("jiu4 shi4", "就是", "just, add emphasis to a statement, exactly, precisely", 3)
dq_vocabulary["然后现在住在香港"] = Vocabulary("ran2 hou4 xian4 zai4 zhu4 zai4 xiang1 gang3", "然后现在住在香港", "Sentence: And(then) now live in Hong Kong", 3)

dq_vocabulary["这些"] = Vocabulary("zhe4 xie1", "这些", "these", 1)
dq_vocabulary["要"] = Vocabulary("yao4", "要", "will, want (direct)", 1)
dq_vocabulary["我要"] = Vocabulary("wo3 yao4", "我要", "i'm going to ... (do something)", 1)
dq_vocabulary["说实话"] = Vocabulary("shuo1 shi2 hua4", "说实话", "honestly ..., to speak the truth, frankly", 2)
dq_vocabulary["只"] = Vocabulary("zhi3", "只", "only, merely, just", 1)
dq_vocabulary["记得"] = Vocabulary("ji4 de", "记得", "to remember (2 words)", 1)
dq_vocabulary["敢"] = Vocabulary("gan3", "敢", "to dare", 2)
dq_vocabulary["点"] = Vocabulary("dian3", "点", "to order (food at a restaurant)", 2)
dq_vocabulary["感觉"] = Vocabulary("gan3 jue2", "感觉", "feeling, perception", 3)
dq_vocabulary["比如"] = Vocabulary("bi3 ru2", "比如", "for example", 2)

dq_vocabulary["开车"] = Vocabulary("kai1 che1", "开车", "to drive (a car)", 1)
dq_vocabulary["药"] = Vocabulary("yao4", "药", "medecine", 1)
dq_vocabulary["吃药"] = Vocabulary("chi1 yao4", "吃药", "to take medicine", 2)
dq_vocabulary["病"] = Vocabulary("bing4", "病", "sickness", 1)
dq_vocabulary["看病"] = Vocabulary("kan4 bing4", "看病", "to diagnose the sickness, to have the sickness checked out", 2)

dq_vocabulary["常常"] = Vocabulary("chang2 chang2", "常常", "frequently, often", 2)
dq_vocabulary["知道"] = Vocabulary("zhi1 dao4", "知道", "to know", 1)
dq_vocabulary["可能"] = Vocabulary("ke3 neng2", "可能", "might (happen), possible, probable", 2)
dq_vocabulary["我花了"] = Vocabulary("wo3 hua1 le", "我花了", "I spent ... (this amount of money)", 1)
dq_vocabulary["穷"] = Vocabulary("qiong2", "穷", "poor, destiture", 1)
dq_vocabulary["反正"] = Vocabulary("fan3 zheng4", "反正", "anyway ..., in any case ...", 3)
dq_vocabulary["高兴"] = Vocabulary("gao1 xing4", "高兴", "happy (intense, great joy), glad", 1)
dq_vocabulary["开心"] = Vocabulary("kai1 xin1", "开心", "happy (general), cheerfulness", 1)

dq_vocabulary["这边"] = Vocabulary("zhe4 bian1", "这边", "here, this side", 1)
dq_vocabulary["服务员"] = Vocabulary("fu2 wu4 yuan2", "服务员", "waiter / waitress", 2)
dq_vocabulary["问"] = Vocabulary("wen4", "问", "to ask / to inquire", 1)
dq_vocabulary["如果"] = Vocabulary("ru2 guo3", "如果", "if, in this case", 1)
dq_vocabulary["尽量"] = Vocabulary("jin3 liang4", "尽量", "as much as possible, to the greatest extent", 1)

#dq_vocabulary[""] = Vocabulary("", "", "", 1)
dq_vocabulary["百"] = Vocabulary("bai3", "百", "hundred", 2)
